- hosts: localhost
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "VDOM10"
    host: "10.87.0.4"
    username: "admin"
    password: "A$Cisc0Admin"
  tasks:
  - name: backup VDOM4
    fortios_system_config_backup_restore:
#    config: "VDOM4 config backup"
     host:  "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom: "{{ vdom }}"
     backup: yes
 #    https: True
 #   ssl_verify: False
 #    scope: "vdom"
     backup_filename: "/tmp/backup_test"
#"Unsupported parameters for (fortios_config) module: 
#config, filename, https, scope, ssl_verify 

#Supported parameters include: 
#backup, backup_filename, backup_path, config_file, file_mode, filter, host, password, src, timeout, username, vdom"}
