- hosts: localhost
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "VDOM10"
    host: "10.87.0.4"
    username: "admin"
    password: "A$Cisc0Admin"
  tasks:
  - name: backup VDOM4
    fortios_system_config_backup_restore:
     config: "VDOM4 config backup"
     host:  "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom: "{{ vdom }}"
     backup: yes
     https: True
     ssl_verify: False
     scope: "vdom"
     filename: "/tmp/backup_test"
